
package gov.gsa.fas.fpdsatomfeed.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import com.fpdsng.fpds.ListOfAwards;
import com.fpdsng.fpds.ListOfIDVs;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "FPDSAtomFeedAccess", targetNamespace = "http://fas.gsa.gov/FPDSAtomFeed/service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FPDSAtomFeedAccess {


    /**
     * 
     * @param parameters
     * @return
     *     returns java.lang.String
     * @throws ServiceFault
     */
    @WebMethod(action = "http://fas.gsa.gov/FPDSAtomFeed/service/getAtomFeed")
    @WebResult(name = "getAtomFeedResponse", targetNamespace = "http://fas.gsa.gov/FPDSAtomFeed/service", partName = "parameters")
    public String getAtomFeed(
        @WebParam(name = "getAtomFeedRequest", targetNamespace = "http://fas.gsa.gov/FPDSAtomFeed/service", partName = "parameters")
        AtomFeedRequest parameters)
        throws ServiceFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns long
     * @throws ServiceFault
     */
    @WebMethod(action = "http://fas.gsa.gov/FPDSAtomFeed/service/getAtomFeedCount")
    @WebResult(name = "getAtomFeedCountResponse", targetNamespace = "http://fas.gsa.gov/FPDSAtomFeed/service", partName = "parameters")
    public long getAtomFeedCount(
        @WebParam(name = "getAtomFeedCountRequest", targetNamespace = "http://fas.gsa.gov/FPDSAtomFeed/service", partName = "parameters")
        AtomFeedRequest parameters)
        throws ServiceFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.fpdsng.fpds.ListOfAwards
     * @throws ServiceFault
     */
    @WebMethod(action = "http://fas.gsa.gov/FPDSAtomFeed/service/getAwardList")
    @WebResult(name = "getAwardListResponse", targetNamespace = "http://fas.gsa.gov/FPDSAtomFeed/service", partName = "parameters")
    public ListOfAwards getAwardList(
        @WebParam(name = "getAwardListRequest", targetNamespace = "http://fas.gsa.gov/FPDSAtomFeed/service", partName = "parameters")
        AtomFeedRequest parameters)
        throws ServiceFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.fpdsng.fpds.ListOfIDVs
     * @throws ServiceFault
     */
    @WebMethod(action = "http://fas.gsa.gov/FPDSAtomFeed/service/getIDVList")
    @WebResult(name = "getIDVListResponse", targetNamespace = "http://fas.gsa.gov/FPDSAtomFeed/service", partName = "parameters")
    public ListOfIDVs getIDVList(
        @WebParam(name = "getIDVListRequest", targetNamespace = "http://fas.gsa.gov/FPDSAtomFeed/service", partName = "parameters")
        AtomFeedRequest parameters)
        throws ServiceFault
    ;

}
