/*
 * @(#)OrderComplaintSqlConstants.java			Aug 14, 2012	
 *
 * Copyright 2012 GSA FAS. All rights reserved.
 * GSA PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package gov.gsa.fas.persistence.order.complaint.service;

/**
 * <code>OrderComplaintSqlConstants</code> defines the queries
 * related to Order complaints persistence.
 *
 * @author  PrasadRNerayanuru
 * @version 1.0
 */

public interface OrderComplaintSqlConstants {

	String INSERT_COMPLAINT = "INSERT INTO D524M3S2 (CMPLNT_KEY, NSN, ITM_NME, CTGRY, CMPLNT_DT, CMPLNT_RCVD_DT," +
				"CMPLNT_ORGNTR_NME,CMPLNT_ORGNTR_ADDR1, CMPLNT_ORGNTR_ADDR2, CMPLNT_ORGNTR_CTY, CMPLNT_ORGNTR_ST," + 
				"CMPLNT_ORGNTR_ZIP, CMPLNT_POC_NME, CMPLNT_POC_PHNE, AGNCY_REQSTN_NBR, NOTFY_TYP, NOTFY_TYP_TXT," +
				"PRCHSE_ORDR_NBR, QNTY_RCVD, QNTY_RJCTD, NTURE_OF_CMPLNT, OPRTN_CNTR, FRML_CNTRCT_NBR, CMPLNT_CLOSED," +
				"NCSC_ORGNTR_FNME, NCSC_ORGNTR_LNME, NCSC_ORGNTR_EMAIL, NCSC_ORGNTR_PHNE, NCSC_ORGNTR_PHNE_EXT," + 
				"LST_MODFD_BY, LST_MODFD_TM, LST_MODFD_DT, MODFY_ACTN) " +
				"VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	String RETRIEVE_COMPLAINT = "SELECT CMPLNT_KEY,CI_CNTRL_NBR,NSN,ITM_NME,CTGRY,CMPLNT_DT,CMPLNT_RCVD_DT," +
				"CMPLNT_ORGNTR_NME,CMPLNT_ORGNTR_ADDR1,CMPLNT_ORGNTR_ADDR2,CMPLNT_ORGNTR_CTY,CMPLNT_ORGNTR_ST," +
				"CMPLNT_ORGNTR_ZIP,CMPLNT_POC_NME,CMPLNT_POC_PHNE,AGNCY_REQSTN_NBR,NOTFY_TYP,NOTFY_TYP_TXT," +
				"PRCHSE_ORDR_NBR,QNTY_RCVD,QNTY_RJCTD,NTURE_OF_CMPLNT,OPRTN_CNTR,FRML_CNTRCT_NBR,INVSTGTN_CLOSED," +
				"CMPLNT_CLOSED,NCSC_ORGNTR_FNME,NCSC_ORGNTR_LNME,NCSC_ORGNTR_EMAIL,NCSC_ORGNTR_PHNE,NCSC_ORGNTR_PHNE_EXT," +
				"LST_MODFD_BY,LST_MODFD_TM,LST_MODFD_DT,MODFY_ACTN FROM D524M3S2 WHERE CMPLNT_KEY=?"; 	

	String UPDATE_COMPLAINT = "UPDATE D524M3S2 SET NSN = ?, ITM_NME=?, CTGRY = ?, CMPLNT_DT =?, CMPLNT_RCVD_DT = ?," +
				"CMPLNT_ORGNTR_NME = ?, CMPLNT_ORGNTR_ADDR1 = ?, CMPLNT_ORGNTR_ADDR2=  ?, CMPLNT_ORGNTR_CTY = ?," +
				"CMPLNT_ORGNTR_ST = ?, CMPLNT_ORGNTR_ZIP = ?, CMPLNT_POC_NME = ?, CMPLNT_POC_PHNE =?, AGNCY_REQSTN_NBR= ?," +
				"NOTFY_TYP = ?, NOTFY_TYP_TXT = ?, PRCHSE_ORDR_NBR = ?, QNTY_RCVD = ?, QNTY_RJCTD = ?, NTURE_OF_CMPLNT = ?," + 
				"OPRTN_CNTR= ?, FRML_CNTRCT_NBR = ?, CMPLNT_CLOSED= ?, NCSC_ORGNTR_FNME = ?, NCSC_ORGNTR_LNME = ?, " + 
				"NCSC_ORGNTR_EMAIL = ?, NCSC_ORGNTR_PHNE = ?, NCSC_ORGNTR_PHNE_EXT = ?, LST_MODFD_BY = ?, LST_MODFD_TM = ?," +
				"LST_MODFD_DT = ?, MODFY_ACTN = ? where CMPLNT_KEY = ?";
	
	String CANCEL_COMPLAINT = "UPDATE D524M3S2 SET CMPLNT_CLOSED= 'Y' where CMPLNT_KEY = ?"; 
	
	String RETRIEVE_INVESTIGATION = "select INVSTGTN_KEY, CI_CNTRL_NBR, FRM_STATS, CIM_KEY, FNAME, MNAME," +
				"LNAME, ALT_PHONE, FAX, GEN_EMAIL, M_CI_M.LST_MODFD_BY, M_CI_M.LST_MODFD_TM, M_CI_M.LST_MODFD_DT," +
				"M_CI_M.MODFY_ACTN, M_QCOMPLAINT_M.OPRTN_CNTR from M_QC_ID_FOR_CI, M_CI_M, M_QCOMPLAINT_M " + 
				"where M_CI_M.CI_CNTRL_NBR= M_QCOMPLAINT_M.CI_CNTRL_NBR AND M_QC_ID_FOR_CI.KEY1=M_CI_M.CIM_KEY " +
				"AND M_QCOMPLAINT_M.CMPLNT_KEY = ?";
	
	String INSERT_COMPLAINT_HISTORY = "INSERT INTO H_QCOMPLAINT_M (CMPLNT_KEY,CI_CNTRL_NBR,NSN,ITM_NME,CTGRY," +
			"CMPLNT_DT,CMPLNT_RCVD_DT,CMPLNT_ORGNTR_NME,CMPLNT_ORGNTR_ADDR1,CMPLNT_ORGNTR_ADDR2,CMPLNT_ORGNTR_CTY," +
			"CMPLNT_ORGNTR_ST,CMPLNT_ORGNTR_ZIP,CMPLNT_POC_NME,CMPLNT_POC_PHNE,AGNCY_REQSTN_NBR,NOTFY_TYP," +
			"NOTFY_TYP_TXT,PRCHSE_ORDR_NBR,QNTY_RCVD,QNTY_RJCTD,NTURE_OF_CMPLNT,OPRTN_CNTR,FRML_CNTRCT_NBR," +
			"INVSTGTN_CLOSED,CMPLNT_CLOSED,NCSC_ORGNTR_FNME,NCSC_ORGNTR_LNME,NCSC_ORGNTR_EMAIL,NCSC_ORGNTR_PHNE," +
			"NCSC_ORGNTR_PHNE_EXT,LST_MODFD_BY,LST_MODFD_TM,LST_MODFD_DT,MODFY_ACTN) " +
			"VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
}
