
package gov.gsa.fas.services.attachment.v1.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AttachmentImplService", targetNamespace = "http://fas.gsa.gov/services/Attachment/v1.0", wsdlLocation = "http://localhost:8080/mtom.services/attachmentservice?wsdl")
public class AttachmentImplService
    extends Service
{

    private final static URL ATTACHMENTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATTACHMENTIMPLSERVICE_EXCEPTION;
    private final static QName ATTACHMENTIMPLSERVICE_QNAME = new QName("http://fas.gsa.gov/services/Attachment/v1.0", "AttachmentImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/mtom.services/attachmentservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATTACHMENTIMPLSERVICE_WSDL_LOCATION = url;
        ATTACHMENTIMPLSERVICE_EXCEPTION = e;
    }

    public AttachmentImplService() {
        super(__getWsdlLocation(), ATTACHMENTIMPLSERVICE_QNAME);
    }

    public AttachmentImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATTACHMENTIMPLSERVICE_QNAME, features);
    }

    public AttachmentImplService(URL wsdlLocation) {
        super(wsdlLocation, ATTACHMENTIMPLSERVICE_QNAME);
    }

    public AttachmentImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATTACHMENTIMPLSERVICE_QNAME, features);
    }

    public AttachmentImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AttachmentImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AttachmentWS
     */
    @WebEndpoint(name = "AttachmentWS")
    public AttachmentWS getAttachmentWS() {
        return super.getPort(new QName("http://fas.gsa.gov/services/Attachment/v1.0", "AttachmentWS"), AttachmentWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AttachmentWS
     */
    @WebEndpoint(name = "AttachmentWS")
    public AttachmentWS getAttachmentWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://fas.gsa.gov/services/Attachment/v1.0", "AttachmentWS"), AttachmentWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATTACHMENTIMPLSERVICE_EXCEPTION!= null) {
            throw ATTACHMENTIMPLSERVICE_EXCEPTION;
        }
        return ATTACHMENTIMPLSERVICE_WSDL_LOCATION;
    }

}
