//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.12-01/26/2011 03:39 PM(mockbuild)-ea 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.31 at 03:43:07 PM EDT 
//


package gov.gsa.fas.vision.dla.request.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for EDI_Element_String_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EDI_Element_String_Type">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" default="Element" />
 *       &lt;attribute name="EDIDataType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Macro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ApplicationInfo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EDI_Element_String_Type", propOrder = {
    "value"
})
@XmlSeeAlso({
    E_1196 .class,
    E_1195 .class,
    E_352 .class,
    E_353 .class,
    E_367 .class,
    E_365 .class,
    E_366 .class,
    E_363 .class,
    E_364 .class,
    E_559 .class,
    E_756 .class,
    E_755 .class,
    E_373 .class,
    E_374 .class,
    E_355_1 .class,
    E_623_1 .class,
    E_888 .class,
    E_673 .class,
    E_98 .class,
    E_93 .class,
    E_96 .class,
    E_559_1 .class,
    E_350_1 .class,
    E_522 .class,
    E_128_1 .class,
    E_128_6 .class,
    E_128_7 .class,
    E_128_2 .class,
    E_128_3 .class,
    E_128_4 .class,
    E_128_5 .class,
    E_66_2 .class,
    E_235_1 .class,
    E_1270_1 .class,
    E_235_2 .class,
    E_98_1 .class,
    E_98_3 .class,
    E_1250_1 .class,
    E_127 .class,
    E_128 .class,
    E_1251_1 .class,
    E_328 .class,
    E_329 .class,
    E_640 .class,
    E_66 .class,
    E_1270 .class,
    E_735 .class,
    E_67 .class,
    E_1271 .class,
    E_234 .class,
    E_235 .class,
    E_337 .class,
    E_1705 .class,
    E_366_1 .class,
    E_628 .class,
    E_443 .class,
    E_374_1 .class,
    E_143 .class
})
public class EDI_Element_String_Type {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "Type")
    protected String type;
    @XmlAttribute(name = "EDIDataType")
    protected String ediDataType;
    @XmlAttribute(name = "Macro")
    protected String macro;
    @XmlAttribute(name = "ApplicationInfo")
    protected String applicationInfo;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Name")
    protected String name;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "Element";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the ediDataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEDIDataType() {
        return ediDataType;
    }

    /**
     * Sets the value of the ediDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEDIDataType(String value) {
        this.ediDataType = value;
    }

    /**
     * Gets the value of the macro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMacro() {
        return macro;
    }

    /**
     * Sets the value of the macro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMacro(String value) {
        this.macro = value;
    }

    /**
     * Gets the value of the applicationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationInfo() {
        return applicationInfo;
    }

    /**
     * Sets the value of the applicationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationInfo(String value) {
        this.applicationInfo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
