//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.12-01/26/2011 03:39 PM(mockbuild)-ea 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.31 at 03:43:07 PM EDT 
//


package gov.gsa.fas.vision.dla.request.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for F_File_842AW complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="F_File_842AW">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="T_Nonconformance_Report_842AW" type="{}T_842" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "F_File_842AW", propOrder = {
    "tNonconformanceReport842AW"
})
public class F_File_842AW {

    @XmlElement(name = "T_Nonconformance_Report_842AW")
    protected List<T_842> tNonconformanceReport842AW;

    /**
     * Gets the value of the tNonconformanceReport842AW property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tNonconformanceReport842AW property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getT_Nonconformance_Report_842AW().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link T_842 }
     * 
     * 
     */
    public List<T_842> getT_Nonconformance_Report_842AW() {
        if (tNonconformanceReport842AW == null) {
            tNonconformanceReport842AW = new ArrayList<T_842>();
        }
        return this.tNonconformanceReport842AW;
    }

}
