//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.12-01/26/2011 03:39 PM(mockbuild)-ea 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.31 at 03:43:07 PM EDT 
//


package gov.gsa.fas.vision.dla.request.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * To indicate the total monetary amount
 * 
 * <p>Java class for S_AMT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S_AMT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="E_Amount_Qualifier_Code" type="{}E_522"/>
 *         &lt;element name="E_Monetary_Amount" type="{}E_782_1"/>
 *         &lt;element name="E_Credit_Debit_Flag_Code" type="{}E_478" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" default="Segment" />
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" default="AMT" />
 *       &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" default="Monetary Amount" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S_AMT", propOrder = {
    "eAmountQualifierCode",
    "eMonetaryAmount",
    "eCreditDebitFlagCode"
})
public class S_AMT {

    @XmlElement(name = "E_Amount_Qualifier_Code", required = true)
    protected E_522 eAmountQualifierCode;
    @XmlElement(name = "E_Monetary_Amount", required = true)
    protected E_782_1 eMonetaryAmount;
    @XmlElementRef(name = "E_Credit_Debit_Flag_Code", type = JAXBElement.class)
    protected JAXBElement<E_478> eCreditDebitFlagCode;
    @XmlAttribute(name = "Type")
    protected String type;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Name")
    protected String name;

    /**
     * Gets the value of the e_Amount_Qualifier_Code property.
     * 
     * @return
     *     possible object is
     *     {@link E_522 }
     *     
     */
    public E_522 getE_Amount_Qualifier_Code() {
        return eAmountQualifierCode;
    }

    /**
     * Sets the value of the e_Amount_Qualifier_Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link E_522 }
     *     
     */
    public void setE_Amount_Qualifier_Code(E_522 value) {
        this.eAmountQualifierCode = value;
    }

    /**
     * Gets the value of the e_Monetary_Amount property.
     * 
     * @return
     *     possible object is
     *     {@link E_782_1 }
     *     
     */
    public E_782_1 getE_Monetary_Amount() {
        return eMonetaryAmount;
    }

    /**
     * Sets the value of the e_Monetary_Amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link E_782_1 }
     *     
     */
    public void setE_Monetary_Amount(E_782_1 value) {
        this.eMonetaryAmount = value;
    }

    /**
     * Gets the value of the e_Credit_Debit_Flag_Code property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link E_478 }{@code >}
     *     
     */
    public JAXBElement<E_478> getE_Credit_Debit_Flag_Code() {
        return eCreditDebitFlagCode;
    }

    /**
     * Sets the value of the e_Credit_Debit_Flag_Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link E_478 }{@code >}
     *     
     */
    public void setE_Credit_Debit_Flag_Code(JAXBElement<E_478> value) {
        this.eCreditDebitFlagCode = ((JAXBElement<E_478> ) value);
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        if (type == null) {
            return "Segment";
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        if (id == null) {
            return "AMT";
        } else {
            return id;
        }
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        if (name == null) {
            return "Monetary Amount";
        } else {
            return name;
        }
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
