
package gov.gsa.fas.services.attachment.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AttachmentWS", targetNamespace = "http://fas.gsa.gov/services/Attachment/v1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    gov.gsa.fas.faults.v1.ObjectFactory.class,
    gov.gsa.fas.services.attachment.v1.ObjectFactory.class
})
public interface AttachmentWS {


    /**
     * 
     * @param attachment
     * @return
     *     returns boolean
     * @throws ServiceFault
     */
    @WebMethod
    @WebResult(name = "success", targetNamespace = "http://fas.gsa.gov/services/Attachment/v1.0", partName = "success")
    public boolean submitAttachmentData(
        @WebParam(name = "attachment", targetNamespace = "http://fas.gsa.gov/services/Attachment/v1.0", partName = "attachment")
        Attachment attachment)
        throws ServiceFault
    ;

}
